name: Star Wars Commit Art

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate Star Wars commits
        run: python scripts/generate.py

      - name: Commit changes
        run: |
          git config user.name "imperial-droid"
          git config user.email "droid@empire.com"

          git add .
          git commit -m "🌌 imperial transmission" || exit 0
          git push
